// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crfvlilmnsovojvcihlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyZnZsaWxtbnNvdm9qdmNpaGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwOTYxNTAsImV4cCI6MjA2MjY3MjE1MH0.CQVXUCWblSFIYy0Ei9eb5DOfmUukq6h58Ql_ZLJAcFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);